module.exports = {
  ERR_UNDEFINED_KEY: 'ERR_UNDEFINED_KEY',
  ERR_UNKOWN_ICON: 'ERR_UNKOWN_ICON',
  ERR_MISSING_FORM_ID: 'ERR_MISSING_FORM_ID',
  ERR_INVALID_NODE: 'ERR_INVALID_NODE',

  // From backend
  ERR_FORM_NOT_FOUND: 'ERR_FORM_NOT_FOUND',
  ERR_INVALID_INPUT: 'ERR_INVALID_INPUT',
  ERR_STEP_VALIDATION_FAILED: 'ERR_STEP_VALIDATION_FAILED',
  ERR_SERVER_ERROR: 'ERR_SERVER_ERROR',
};
